#!/bin/bash
# File: /etc/libvirt/hooks/qemu
# (c) 2016 www.sosyco.de email: sosyco@googlemail.com
# Based on: http://wiki.libvirt.org/page/Networking#Forwarding_Incoming_Connections

# Update the following variables to fit your setup
Host_ipaddr=<ipaddr of eth0>
IPFIRE_name=<name of your IPFIRE-VM>
IPFIRE_ipaddr=192.168.122.2
IPFIRE_portranges=( '0:21' '23:65500') # typical port 22 to the host, all other to IPFIRE
#
# IPFIRE-NAT-RULES
length=$(( ${#IPFIRE_portranges[@]} - 1 ))
if [ "${1}" = "${IPFIRE_name}" ]; then
   if [ "${2}" = "stopped" ] || [ "${2}" = "reconnect" ]; then
        for i in `seq 0 $length`; do
                iptables -t nat -D PREROUTING -d ${Host_ipaddr} -p tcp -m tcp --dport ${IPFIRE_portranges[$i]} -j DNAT --to-destination ${IPFIRE_ipaddr}  #tcp port range
                iptables -t nat -D PREROUTING -d ${Host_ipaddr} -p udp -m udp --dport ${IPFIRE_portranges[$i]} -j DNAT --to-destination ${IPFIRE_ipaddr}  #udp port range
                iptables -D FORWARD -d ${IPFIRE_ipaddr}/32 -p tcp -m state --state NEW -m tcp --dport ${IPFIRE_portranges[$i]} -j ACCEPT #forward tcp port range
                iptables -D FORWARD -d ${IPFIRE_ipaddr}/32 -p udp -m state --state NEW -m udp --dport ${IPFIRE_portranges[$i]} -j ACCEPT #forward udp port range
        done
   fi
   if [ "${2}" = "start" ] || [ "${2}" = "reconnect" ]; then
        for i in `seq 0 $length`; do
                iptables -t nat -A PREROUTING -d ${Host_ipaddr} -p tcp -m tcp --dport ${IPFIRE_portranges[$i]} -j DNAT --to-destination ${IPFIRE_ipaddr}  #tcp port range
                iptables -t nat -A PREROUTING -d ${Host_ipaddr} -p udp -m udp --dport ${IPFIRE_portranges[$i]} -j DNAT --to-destination ${IPFIRE_ipaddr}  #udp port range
                iptables -I FORWARD -d ${IPFIRE_ipaddr}/32 -p tcp -m state --state NEW -m tcp --dport ${IPFIRE_portranges[$i]} -j ACCEPT #forward tcp port range
                iptables -I FORWARD -d ${IPFIRE_ipaddr}/32 -p udp -m state --state NEW -m udp --dport ${IPFIRE_portranges[$i]} -j ACCEPT #forward udp port range
        done
   fi
fi
